### PR TITLE
Repo.py

### PR DESCRIPTION
**Pull request by lf-**
Implement a tool to simplify management of clones of all the electrical repos. It uses Python's `asyncio` to perform operations on several repositories in parallel. The goal is that you can check out `Electrical` then quickly get set up with all the projects, as well as ensure that you cannot submit changes without libraries being up to date. This will also ensure everyone has a standard directory structure for their development environment.

Unlike the one other tool that might have made sense for this application, Google's `repo`, this does not demand anything different in your workflow: the repositories cloned by this one are completely normal clones that you work with normally in regard to committing, pushing, branching, etc.

## Setup

Ensure you have Python 3.7 or above installed.

```
# you can also use https
git clone git@github.com:UBC-ThunderBots/Electrical
cd Electrical
# pass --https if you use git with https rather than ssh
./repo.py init
```

## You can

* Clone all the repos at once with `./repo.py init`
* Pull all of them with `./repo.py pull`
* Check where your local copies are in relation to the versions on GitHub with `./repo.py status`
* Run arbitrary commands in parallel on the repos with `./repo.py forall {cmd}`

## Automated work

* It automatically inserts a git hook in each cloned repo that blocks pushes if libraries are not up to date.
* It will manage your gitignore for the Electrical repo so that all of its repos are excluded from your clone of Electrical.

Final note:

I updated `README.md` to explain how the tool works, but it's just the README I wrote when doing README-driven development concatenated onto the end of ours. Your call as to whether to move some or all of that documentation elsewhere.

### CODE REVIEW

**Comment by lf-** [comment]
image

This is what happens if you try to push if your libraries are not the same as the ones on GitHub (this includes having local changes).

**Comment by lf-** [comment]
Update: Based on a discussion with @hannahvsawiuk, @garethellis0 and @MathewMacDougall, this has been updated to support a new workflow where its main use is installing a hook to ensure that libraries are up to date in repositories that use them.

We now have the following message:

image

**Comment by liambontkes** [comment]
I thought we agreed in slack that we were going to move forward with a shell based based solution? While I agree that this will be very useful for new members, I think that relying on Python adds complexity that will make it difficult for novices to use/setup. Would it be feasible to transpose this work into a shell script?

**Comment by lf-** [comment]
Yes. It wouldn't be *that* hard to do, but it would be appreciably less maintainable (who has a reasonably high degree of shell *scripting* proficiency [a distinctly different skill than normal shell usage] on the team vs Python?) and have worse user interface. Such a conversion is possible though, since after installation it is already the case that you don't have to have Python at all. 

I was not aware that there was any such consensus on slack.

**Comment by garethellis0** [comment]
From the software teams experience, we've found simple bash scripts are significantly easier to maintain and more robust for this sort of simple thing. It would probably be less then 50 lines, and since the current functionality required is just a setup script, there's really no user interface other then just running it.

**Comment by lf-** [comment]
This is obsolete. #10 does the main part of what this did.

**Pull request closed without merging**
